### ISSUE TITLE
Constant tensor with more than one dimension

### ISSUE THREAD

**Issue by yongfei25** [twitter/torch-autograd#66]
Hi, been hitting into this error quite frequently. Have this error when I declare a new Tensor and pass it into a torch function.

```lua
local d = require 'autograd'
d.optimize(true)

local lossf = d.nn.ClassNLLCriterion()
local f = function(params, y)
  local yhat = torch.Tensor(2, 400003):uniform(-0.1,0.1)

  -- also, if you uncomment this block, the autograd will print out the entire tensor :\
  -- local t = {
  --   torch.Tensor(400003):double():uniform(-0.1, 0.1),
  --   torch.Tensor(400003):double():uniform(-0.1, 0.1)
  -- }
  -- yhat = torch.cat(t,1)

  local loss = lossf(yhat, y)
  return loss
end

local df = d(f)
local y = torch.Tensor({9516,400003})
local params = {}

df(params, y)

```

```
/torch/install/bin/luajit: .../install/share/lua/5.1/autograd/runtime/codegen/Node.lua:25: constant tensor with more than one dimension. is this an upvalue that should be a function argument?
stack traceback:
	[C]: in function 'error'
	.../install/share/lua/5.1/autograd/runtime/codegen/Node.lua:25: in function 'init'
	.../install/share/lua/5.1/autograd/runtime/codegen/Node.lua:10: in function 'new'
	...install/share/lua/5.1/autograd/runtime/codegen/Graph.lua:19: in function 'lossf'
	train.lua:154: in function 'fn'
	...install/share/lua/5.1/autograd/runtime/codegen/Graph.lua:281: in function 'protectedFn'
	...install/share/lua/5.1/autograd/runtime/codegen/Graph.lua:309: in function 'record'
	.../install/share/lua/5.1/autograd/runtime/codegen/init.lua:44: in function 'generateFn'
	.../install/share/lua/5.1/autograd/runtime/codegen/init.lua:66: in function 'df'
	train.lua:161: in main chunk
	[C]: in function 'dofile'
	...gfei/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406670
```

**Comment by yongfei25** [comment]
I use switched to code below and it is working fine now.
If this is expected, then this issue is solved. :)

```lua
torch.uniform(torch.zero(params.w.new(2, 400003)))
```

**Comment by ngoodman** [comment]
I've run into this a bunch, too. I believe it is because codegen is unwilling to tape-ify a constant tensor (i.e. upgrade it to a Value to that it can flow along the AD computation). I'm not sure if that is by design or just something that hasn't gotten cleaned up yet.

A work-around is to pass the constant tensor into the target function as an argument. So for your above code something like:
~~~
local yhat = torch.Tensor(2, 400003):uniform(-0.1,0.1)
local f = function(params, y,yhat)
  ...
~~~
However, it's pretty annoying to have to do this all the time. It would be great if either constant tensors could be upgraded automatically, or if a Constant() util could be provided to do this by hand.

(Note that this error doesn't happen in non-optimizing mode. It's slightly disconcerting that one errors on constant tensors and the other doesn't blink!)

**Comment by alexbw** [comment]
Yeah, we should be throwing much better errors here. 
Also (and we should be throwing errors for this, too), we don't support any calls to `self` inside an autograd'd function. So stuff like `myTensor:view(10,10)` is invalid, and instead you should use `torch.view(myTensor,10,10)`. 
I'm not sure if we have a call to `torch.uniform()` added, though.

**Comment by luketwitter** [comment]
So the root issue is that the operation:
```
local yhat = torch.Tensor(2, 400003):uniform(-0.1,0.1)
```
Isn't tracked by autograd, so we have no idea where that tensor came from, and assumes it's some upvalue constant. Since the optimized mode is producing standalone lua code for your function, any constants have to become literals in the code. This isn't really practical for large tensors, so I limit it to smaller 1D tensors.

(the fix you made is the right thing to do)
