### ISSUE TITLE
Error "attempt to compare number with table" when parameters involved in comparison

### ISSUE THREAD

**Issue by m-hahn** [twitter/torch-autograd#79]
I would like to differentiate functions involving Bernoulli trials whose probabilities depend on the parameters, where I would like the result of the trial to be treated as a constant by the differentiation.
The following code, which tries to do that, raises "attempt to compare number with table":

    t = require 'torch'
    grad = require 'autograd'
    
    params = {
       a = t.randn(1,1)
    }

    f = function(params, x)
       local result = t.sum(x * params.a)
    
       -- sample from Bernoulli dist
       local bernoulli = torch.FloatTensor(1):zero()
       if torch.uniform() < t.sum(params.a) then
             bernoulli[1] = 1
       end
  
       return t.sum(bernoulli * result)
    end

    df = grad(f)

    x = t.randn(1,1)

    print(f(params, x))

    print(df(params, x))

Replacing the `if` block by `decision[1] = t.bernoulli(t.sum(params.a))`, which should do the same thing, also raises an error. Replacing the condition by `0.5 < t.sum(params.a)` does not eliminate the error, which seems to show that the problem is not the use of random numbers.

Is there a way to tell autograd not to try to differentiate through comparisons and instead treat the resulting truth values as constants (which is possible in Theano)?

**Comment by alexbw** [comment]
Good catch, this is because we don't have `__lt`metamethod defined internally. I'll add this.

**Comment by alexbw** [comment]
An update — 
We will not be able to support `<,<=,>,>=,==` operations, because Lua requires that the variables on either side of the comparison have the same type. This will not be true in autograd, because we wrap all values in objects to keep track of how they're used in the forward pass, to automatically infer the backward pass.

So, I added `util.le`, `util.lt`, `util.ge`, `util.gt`, `util.eq` so you can make comparisons safely in autograd. See the [new LessThan test](https://github.com/twitter/torch-autograd/blob/b798a5d5bb0a37a9a518923d957a0e51955aa546/test/test.lua#L1338-L1351).

You're also keeping track of values in a dynamically-allocated array. This is the next thing we'll have to tackle, because autograd doesn't support assignment to arrays (autograd requires all method calls be pure functions). I'll make a little utility that could help with that.

**Comment by alexbw** [comment]
We added support for comparisons, as I mentioned above, and also now support concatenating numbers, using our own `autograd.util.cat` function. It currently only supports catting variables of the same type (e.g. all FloatTensors or all numbers), and will probably stay that way for awhile, unless specific requests come up.

I modified your example only slightly, so please try this now:

```lua
t = require 'torch'
local grad = require 'autograd'
local util = require 'autograd.util'

params = {
   a = t.randn(1,1)
}

f = function(params, x)
   local result = t.sum(x * params.a)

   -- sample from Bernoulli dist
   local bernoulli = {}
   if util.lt(torch.uniform(), t.sum(params.a)) then
         bernoulli[1] = 1
   end

   return t.sum(util.cat(bernoulli) * result)
end

df = grad(f)
x = t.randn(1,1)
print(f(params, x))
print(df(params, x))
```

By the way, if you want to use optimized mode (`autograd(f, {optimize=true})`), you will have to pre-generate the random numbers, and put them in the `params` table. Otherwise, the `if` statement will be optimized away entirely (we can't overload, and thus can't track, control flow in optimized mode).

**Comment by alexbw** [comment]
Closing. Reopen if something is wrong.
